FROM golang:latest as builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o main .

FROM debian:stable-slim

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
